services:
  chatbot:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"


